[theme]
primaryColor = "#1E2250"             # Amarelo - similar ao botão do Mercado Livre
backgroundColor = "#eae9ea"          # Amarelo claro para o fundo
secondaryBackgroundColor = "#ffffff" # Azul claro para fundo dos widgets
textColor = "#2d377a"                # Azul - similar ao texto do Mercado Livre
font = "sans serif"
